apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgresCredentials.username | quote }}
  password: {{ .Values.postgresCredentials.password | quote }}
  database: {{ .Values.postgresCredentials.database | quote }}
